name: Develop Pipeline

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        environment: develop
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install dependencies
              run: npm install --no-audit --no-fund --no-optional
            - name: Lint
              run: npm run eslint
            - name: Build
              run: npm run build
            - name: Test
              run: npm test
            - name: Deploy to Render
              uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
              with:
                serviceId: ${{ secrets.RENDER_SERVICE_ID }}
                apiKey: ${{ secrets.RENDER_API_KEY }}
                multipleDeployment: false #optional, default true