name: Pipeline

on:
    push:
        branches:
            - main
jobs:
    test_message:
        environment: production
        runs-on: ubuntu-20.04
        steps:
            - name: Message
              run: |
                echo "Hola Mundo!!!"